language: go

go:
  - 1.9.x
  - master

before_install:
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/fatih/color
  - go get github.com/hashicorp/go-getter
  - go get github.com/hashicorp/go-version
  - go get github.com/urfave/cli

script:
  - go test -v ./...
